### ISSUE TITLE
NullReferenceException if ProjectReference is missing Guid

### ISSUE THREAD

**Issue by jazzdev** [themotleyfool/SlimJim#9]
Some of my .csproj files don't have a guid in the ProjectReference

    <ProjectReference Include="Whereever\Whatever.csproj">
      <Name>Whatever</Name>
    </ProjectReference>

That causes SlimJim to crash:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at SlimJim.Infrastructure.CsProjReader.<ReadReferencedProjectGuids>b__5(XElement pr) in c:\Users\jd.brennan\src\SlimJim\src\SlimJim\Infrastructure\CsProjReader.cs:line 66
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SlimJim.Infrastructure.CsProjReader.ReadReferencedProjectGuids(XElement xml) in c:\Users\jd.brennan\src\SlimJim\src\SlimJim\Infrastructure\CsProjReader.cs:line 65
   at SlimJim.Infrastructure.CsProjReader.Read(FileInfo csProjFile) in c:\Users\jd.brennan\src\SlimJim\src\SlimJim\Infrastructure\CsProjReader.cs:line 25
   at SlimJim.Infrastructure.CsProjRepository.<ReadProjectFilesIntoCsProjObjects>b__0(FileInfo f) in c:\Users\jd.brennan\src\SlimJim\src\SlimJim\Infrastructure\CsProjRepository.cs:line 50
   at System.Collections.Generic.List`1.ConvertAll[TOutput](Converter`2 converter)
   at SlimJim.Infrastructure.CsProjRepository.ReadProjectFilesIntoCsProjObjects(List`1 files) in c:\Users\jd.brennan\src\SlimJim\src\SlimJim\Infrastructure\CsProjRepository.cs:line 50
   at SlimJim.Infrastructure.CsProjRepository.LookupCsProjsFromDirectory(SlnGenerationOptions options) in c:\Users\jd.brennan\src\SlimJim\src\SlimJim\Infrastructure\CsProjRepository.cs:line 23
   at SlimJim.SlnFileGenerator.GenerateSolutionFile(SlnGenerationOptions options) in c:\Users\jd.brennan\src\SlimJim\src\SlimJim\SlnFileGenerator.cs:line 27
   at SlimJim.SlimJimMain.Main(String[] args) in c:\Users\jd.brennan\src\SlimJim\src\SlimJim\SlimJimMain.cs:line 31
```

**Comment by chriseldredge** [comment]
Fixed by #10.
